#!/bin/bash

# 📋 Comandos para Copiar y Pegar en EC2 Instance Connect
# Copia estos comandos y pégalos uno por uno en la terminal de EC2 Instance Connect

echo "🔧 Comandos para Arreglar Instancia Staging"
echo "=============================================="
echo ""
echo "Copia y pega estos comandos UNO POR UNO en EC2 Instance Connect:"
echo ""
echo "---"
echo ""
echo "# 1. Deshabilitar firewall"
echo "sudo ufw --force disable"
echo "sudo iptables -F"
echo "sudo iptables -X"
echo "sudo iptables -P INPUT ACCEPT"
echo "sudo iptables -P FORWARD ACCEPT"
echo "sudo iptables -P OUTPUT ACCEPT"
echo ""
echo "# 2. Verificar e iniciar servicios"
echo "sudo systemctl status ssh"
echo "sudo systemctl start ssh"
echo "sudo systemctl enable ssh"
echo "sudo systemctl status nginx"
echo "sudo systemctl start nginx"
echo "sudo systemctl enable nginx"
echo "sudo systemctl status php8.2-fpm"
echo "sudo systemctl start php8.2-fpm"
echo "sudo systemctl enable php8.2-fpm"
echo ""
echo "# 3. Configurar permisos"
echo "sudo chown -R www-data:www-data /var/www/magicai/storage /var/www/magicai/bootstrap/cache"
echo "sudo chmod -R 775 /var/www/magicai/storage /var/www/magicai/bootstrap/cache"
echo "sudo mkdir -p /var/www/magicai/storage/framework/{cache,sessions,views,testing} /var/www/magicai/storage/logs"
echo ""
echo "# 4. Verificar HTTP funciona"
echo "curl http://localhost"
echo ""
echo "# 5. Verificar Nginx"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""
echo "# 6. Verificar puertos"
echo "sudo ss -tlnp | grep :22"
echo "sudo ss -tlnp | grep :80"
echo ""
echo "# 7. Configurar firewall (AL FINAL)"
echo "sudo ufw allow 22/tcp"
echo "sudo ufw allow 80/tcp"
echo "sudo ufw allow 443/tcp"
echo "sudo ufw --force enable"
echo ""
echo "# 8. Verificar firewall"
echo "sudo ufw status"
echo ""
echo "---"
echo ""
echo "✅ Después de ejecutar estos comandos, prueba desde tu Mac:"
echo "   ssh -4 -i staging-tausepro-key.pem ubuntu@44.211.83.213"
echo "   curl http://test.tause.pro"
echo ""



